from django.urls import include, path
from .views import (UserListCreateView, UserDetailView, RecipeListCreateView,
                    RecipeDetailView, IngredientListView, IngredientDetailView,
                    SubscriptionListCreateView, SubscriptionDetailView,
                    FavoriteListCreateView, FavoriteDetailView,
                    ShoppingCartListCreateView, ShoppingCartDetailView,
                    CurrentUserView, UserAvatarView, SetPasswordView,
                    SubscribeView, SubscriptionsListView,
                    DownloadShoppingCartView, GetShortLinkView,
                    FavoriteAddView, ShoppingCartAddView)


urlpatterns = [
    path('users/', UserListCreateView.as_view(), name='user-list'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('users/me/', CurrentUserView.as_view(), name='current-user'),
    path('users/me/avatar/', UserAvatarView.as_view(), name='user-avatar'),
    path('users/set_password/', SetPasswordView.as_view(),
         name='set-password'),
    path('users/<int:id>/subscribe/', SubscribeView.as_view(),
         name='subscribe'),
    path('users/subscriptions/', SubscriptionsListView.as_view(),
         name='subscriptions-list'),
    path('recipes/', RecipeListCreateView.as_view(), name='recipe-list'),
    path('recipes/<int:pk>/', RecipeDetailView.as_view(),
         name='recipe-detail'),
    path('recipes/<int:pk>/favorite/', FavoriteAddView.as_view(),
         name='favorite-add'),
    path('recipes/<int:pk>/shopping_cart/', ShoppingCartAddView.as_view(),
         name='shopping-cart-add'),
    path('recipes/download_shopping_cart/',
         DownloadShoppingCartView.as_view(), name='download-shopping-cart'),
    path('recipes/<int:id>/get-link/',
         GetShortLinkView.as_view(), name='get-short-link'),
    path('ingredients/', IngredientListView.as_view(), name='ingredient-list'),
    path('ingredients/<int:pk>/', IngredientDetailView.as_view(),
         name='ingredient-detail'),
    path('subscriptions/', SubscriptionListCreateView.as_view(),
         name='subscription-list'),
    path('subscriptions/<int:pk>/', SubscriptionDetailView.as_view(),
         name='subscription-detail'),
    path('favorites/', FavoriteListCreateView.as_view(), name='favorite-list'),
    path('favorites/<int:pk>/', FavoriteDetailView.as_view(),
         name='favorite-detail'),
    path('shopping_carts/', ShoppingCartListCreateView.as_view(),
         name='shoppingcart-list'),
    path('shopping_carts/<int:pk>/', ShoppingCartDetailView.as_view(),
         name='shoppingcart-detail'),
    path('auth/', include('djoser.urls.authtoken')),
]
